default:  # ideal to show the temporal blurring effect of binning, but spatial details are not that much.
  reference_directory: none
  # reference_directory: results/kcl_cmr/nufft_t20
  # reference_directory: results/kcl_cmr/grasp_t40/     # Reference image directory, set to none if there is no reference
  comparison_directories:                         # Comparison results directories, can add arbitrary number of comparisons
    - results/kcl_cmr_bak/nufft_t80
    - results/kcl_cmr_bak/nufft_t40
    - results/kcl_cmr_bak/nufft_t20
    - results/kcl_cmr_bak/grasp_t80
    - results/kcl_cmr_bak/grasp_t40
    - results/kcl_cmr_bak/grasp_t20
    # - results/kcl_cmr/subspace_inr_t80                # The last one is the proposed method, and if the sizes of the comparison directories are different, the others will be center cropped to the size of the reference
    - results/kcl_cmr_bak/subspace_inr                # The last one is the proposed method, and if the sizes of the comparison directories are different, the others will be center cropped to the size of the reference
    - results/kcl_cmr_bak/subspace_inr_t40                # The last one is the proposed method, and if the sizes of the comparison directories are different, the others will be center cropped to the size of the reference
  comparison_titles:                              # Titles for each comparison result
    - NUFFT (10 spokes/bin)
    - NUFFT (20 spokes/bin)
    - NUFFT (40 spokes/bin)
    - GRASP (10 spokes/bin)
    - GRASP (20 spokes/bin)
    - GRASP (40 spokes/bin)
    - Proposed (binning-free)
    - Proposed (binning-freem 40t)
  case_id: CINE_S4_GN_GN                        # Case identifier
  # case_id: CINE_S4_GN_GN                          # Case identifier
  phase_index: 20                                  # The phase (frame) to be shown in the figure
  y_profile_index: 77                              # The x-t profile at which y index
  roi_coordinates: [40, 55, 110, 125]              # The zoomed ROI area
  poi_coordinates: [95, 65]                        # The point of interest (POI) coordinates within the ROI, [x, y], increase x to the right and y to the bottom
  arrow_direction: [-5, 5]                          # The direction of the POI arrow, [-1, -1] points to the right bottom.
  t_poi_coordinates: [39, 30]                      # The point of interest (POI) coordinates within the x-t profile, [x, t], increase x to the right and y to the bottom
  t_arrow_direction: [10, 0]                        # The direction of the POI arrow, [1, 1] points to the right top.
  display_range: [0, 0.7]                          # Display range for images
  error_display_range: [0, 0.1]                    # Display range for error maps

good1:  # ideal to show the temporal blurring effect of binning, but spatial details are not that much.
  reference_directory: none
  # reference_directory: results/kcl_cmr/nufft_t20
  # reference_directory: results/kcl_cmr/grasp_t40/     # Reference image directory, set to none if there is no reference
  comparison_directories:                         # Comparison results directories, can add arbitrary number of comparisons
    # - results/kcl_cmr_bak/nufft_t40
    # - results/kcl_cmr_bak/nufft_t20
    # - results/kcl_cmr_bak/grasp_t40
    # - results/kcl_cmr_bak/grasp_t20
    - results/kcl_cmr_bak/subspace_inr_t80_nopretrain                # The last one is the proposed method, and if the sizes of the comparison directories are different, the others will be center cropped to the size of the reference
    - results/kcl_cmr_bak/subspace_inr_t80                # The last one is the proposed method, and if the sizes of the comparison directories are different, the others will be center cropped to the size of the reference
  comparison_titles:                              # Titles for each comparison result
    # - NUFFT (20 spokes/bin)
    # - NUFFT (40 spokes/bin)
    # - GRASP (20 spokes/bin)
    # - GRASP (40 spokes/bin)
    - Proposed (binning-free;No pretrain)
    - Proposed (binning-free)
  case_id: CINE_S1_rad_Nic                        # Case identifier
  # case_id: CINE_S2_rad_Nic                        # Case identifier
  # case_id: CINE_S4_GN_GN                          # Case identifier
  phase_index: 34                                  # The phase (frame) to be shown in the figure
  y_profile_index: 77                              # The x-t profile at which y index
  roi_coordinates: [35, 35, 105, 105]              # The zoomed ROI area
  poi_coordinates: [95, 55]                        # The point of interest (POI) coordinates within the ROI, [x, y], increase x to the right and y to the bottom
  arrow_direction: [-5, 5]                          # The direction of the POI arrow, [-1, -1] points to the right bottom.
  t_poi_coordinates: [31, 14]                      # The point of interest (POI) coordinates within the x-t profile, [x, t], increase x to the right and y to the bottom
  t_arrow_direction: [10, 0]                        # The direction of the POI arrow, [1, 1] points to the right top.
  display_range: [0, 0.6]                          # Display range for images
  error_display_range: [0, 0.1]                    # Display range for error maps

good2:   # good temporal resolution, but spatial details doesn't match well between grasp and subspace inr
  reference_directory: none
  # reference_directory: results/kcl_cmr/nufft_t20
  # reference_directory: results/kcl_cmr/grasp_t40/     # Reference image directory, set to none if there is no reference
  comparison_directories:                         # Comparison results directories, can add arbitrary number of comparisons
    - results/kcl_cmr/nufft_t40
    - results/kcl_cmr/nufft_t20
    - results/kcl_cmr/grasp_t40
    - results/kcl_cmr/grasp_t20
    # - results/kcl_cmr/grasp_t80
    - results/kcl_cmr/subspace_inr                # The last one is the proposed method, and if the sizes of the comparison directories are different, the others will be center cropped to the size of the reference
  comparison_titles:                              # Titles for each comparison result
    - NUFFT (20 spokes/bin)
    - NUFFT (40 spokes/bin)
    - GRASP (20 spokes/bin)
    - GRASP (40 spokes/bin)
    - Proposed (binning-free)
  case_id: CINE_S1_rad_Mig                        # Case identifier
  phase_index: 35                                  # The phase (frame) to be shown in the figure
  y_profile_index: 77                              # The x-t profile at which y index
  roi_coordinates: [35, 45, 105, 115]              # The zoomed ROI area
  poi_coordinates: [95, 58]                        # The point of interest (POI) coordinates within the ROI, [x, y], increase x to the right and y to the bottom
  arrow_direction: [-5, 5]                          # The direction of the POI arrow, [-1, -1] points to the right bottom.
  t_poi_coordinates: [35, 24]                      # The point of interest (POI) coordinates within the x-t profile, [x, t], increase x to the right and y to the bottom
  t_arrow_direction: [10, 0]                        # The direction of the POI arrow, [1, 1] points to the right top.
  display_range: [0, 0.6]                          # Display range for images
  error_display_range: [0, 0.1]                    # Display range for error maps

good3:  # ideal to show both temporal and spatial resolution
  reference_directory: none
  # reference_directory: results/kcl_cmr/nufft_t20
  # reference_directory: results/kcl_cmr/grasp_t40/     # Reference image directory, set to none if there is no reference
  comparison_directories:                         # Comparison results directories, can add arbitrary number of comparisons
    - results/kcl_cmr/nufft_t40
    - results/kcl_cmr/nufft_t20
    - results/kcl_cmr/grasp_t40
    - results/kcl_cmr/grasp_t20
    # - results/kcl_cmr/grasp_t80
    - results/kcl_cmr/subspace_inr                # The last one is the proposed method, and if the sizes of the comparison directories are different, the others will be center cropped to the size of the reference
  comparison_titles:                              # Titles for each comparison result
    - NUFFT (20 spokes/bin)
    - NUFFT (40 spokes/bin)
    - GRASP (20 spokes/bin)
    - GRASP (40 spokes/bin)
    - Proposed (binning-free)
  case_id: CINE_S1_rad_Nic                        # Case identifier
  phase_index: 10                                  # The phase (frame) to be shown in the figure
  y_profile_index: 77                              # The x-t profile at which y index
  roi_coordinates: [35, 36, 105, 106]              # The zoomed ROI area
  poi_coordinates: [85, 45]                        # The point of interest (POI) coordinates within the ROI, [x, y], increase x to the right and y to the bottom
  arrow_direction: [-5, 5]                          # The direction of the POI arrow, [-1, -1] points to the right bottom.
  t_poi_coordinates: [32, 17]                      # The point of interest (POI) coordinates within the x-t profile, [x, t], increase x to the right and y to the bottom
  t_arrow_direction: [10, 0]                        # The direction of the POI arrow, [1, 1] points to the right top.
  display_range: [0, 0.6]                          # Display range for images
  error_display_range: [0, 0.1]                    # Display range for error maps

good5:  # best so far
  reference_directory: none
  # reference_directory: results/kcl_cmr/nufft_t20
  # reference_directory: results/kcl_cmr/grasp_t40/     # Reference image directory, set to none if there is no reference
  comparison_directories:                         # Comparison results directories, can add arbitrary number of comparisons
    - results/kcl_cmr/nufft_t40
    - results/kcl_cmr/nufft_t20
    - results/kcl_cmr/grasp_t40
    - results/kcl_cmr/grasp_t20
    - results/kcl_cmr/subspace_inr_t40                # The last one is the proposed method, and if the sizes of the comparison directories are different, the others will be center cropped to the size of the reference
  comparison_titles:                              # Titles for each comparison result
    - NUFFT (20 spokes/bin)
    - NUFFT (40 spokes/bin)
    - GRASP (20 spokes/bin)
    - GRASP (40 spokes/bin)
    - Proposed (binning-free)
  case_id: CINE_S4_GN_GN                        # Case identifier
  # case_id: CINE_S4_GN_GN                          # Case identifier
  phase_index: 10                                  # The phase (frame) to be shown in the figure
  y_profile_index: 77                              # The x-t profile at which y index
  roi_coordinates: [40, 55, 110, 125]              # The zoomed ROI area
  poi_coordinates: [95, 65]                        # The point of interest (POI) coordinates within the ROI, [x, y], increase x to the right and y to the bottom
  arrow_direction: [-5, 5]                          # The direction of the POI arrow, [-1, -1] points to the right bottom.
  t_poi_coordinates: [39, 14]                      # The point of interest (POI) coordinates within the x-t profile, [x, t], increase x to the right and y to the bottom
  t_arrow_direction: [10, 0]                        # The direction of the POI arrow, [1, 1] points to the right top.
  display_range: [0, 0.7]                          # Display range for images
  error_display_range: [0, 0.1]                    # Display range for error maps

good6:  # okish
  reference_directory: none
  # reference_directory: results/kcl_cmr/nufft_t20
  # reference_directory: results/kcl_cmr/grasp_t40/     # Reference image directory, set to none if there is no reference
  comparison_directories:                         # Comparison results directories, can add arbitrary number of comparisons
    - results/kcl_cmr/nufft_t40
    - results/kcl_cmr/nufft_t20
    - results/kcl_cmr/grasp_t40
    - results/kcl_cmr/grasp_t20
    - results/kcl_cmr/subspace_inr_t40                # The last one is the proposed method, and if the sizes of the comparison directories are different, the others will be center cropped to the size of the reference
  comparison_titles:                              # Titles for each comparison result
    - NUFFT (20 spokes/bin)
    - NUFFT (40 spokes/bin)
    - GRASP (20 spokes/bin)
    - GRASP (40 spokes/bin)
    - Proposed (binning-free)
  case_id: CINE_S3_rad_MM                        # Case identifier
  # case_id: CINE_S4_GN_GN                          # Case identifier
  phase_index: 10                                  # The phase (frame) to be shown in the figure
  y_profile_index: 70                              # The x-t profile at which y index
  roi_coordinates: [40, 50, 110, 120]              # The zoomed ROI area
  poi_coordinates: [95, 65]                        # The point of interest (POI) coordinates within the ROI, [x, y], increase x to the right and y to the bottom
  arrow_direction: [-5, 5]                          # The direction of the POI arrow, [-1, -1] points to the right bottom.
  t_poi_coordinates: [39, 14]                      # The point of interest (POI) coordinates within the x-t profile, [x, t], increase x to the right and y to the bottom
  t_arrow_direction: [10, 0]                        # The direction of the POI arrow, [1, 1] points to the right top.
  display_range: [0, 0.7]                          # Display range for images
  error_display_range: [0, 0.1]                    # Display range for error maps
